apiVersion: v1
kind: PersistentVolumeClaim
  labels:
    app: jenkins
  name: jenkins-test-pv-claim
  namespace: jenkins-test
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: vmware-default
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
~
~
