#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: jenkins-test-pv-claim
#  labels:
#    app: jenkins-test
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 10Gi
#  storageClassName: vmware-default
#
#---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: jenkins-test
  name: jenkins-test
  namespace: jenkins
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins-test
    spec:
      containers:
        - name: jenkins-test
          image: amitjoshi/jenkins:8
          env:
            - name: JAVA_OPTS
              value: -Djenkins.install.runSetupWizard=false
            - name: DOCKER_HOST 
              value: tcp://localhost:2375 
          ports:
            - name: http-port
              containerPort: 8080
            - name: jnlp-port
              containerPort: 50000
#          resources:
#           requests:
#            cpu: "2"
#            memory: 20Gi
          securityContext:
           capabilities:
             add:
             - NET_ADMIN
             - SYS_TIME
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
            - mountPath: /var/jenkins_home/certs
              name: jenkins-ssl-keystore-cert
            - mountPath: /var/jenkins_home/certs/k8s
              name: jenkins-k8s-ca-cert
        - name: dind-daemon 
          image: docker:1.12.6-dind 
#          resources: 
#            requests: 
#                cpu: 20m 
#                memory: 512Mi 
          securityContext: 
             privileged: true 
          volumeMounts: 
            - name: docker-graph-storage 
              mountPath: /var/lib/docker 
      securityContext:
         fsGroup: 1000
         runAsUser: 0
      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-test-pv-claim
        - name: jenkins-ssl-keystore-cert
          secret:
             defaultMode: 420
             secretName: ssl-keystore-cert
        - name: jenkins-k8s-ca-cert
          secret:
             defaultMode: 420
             secretName: k8s-ca-cert
        - name: docker-graph-storage 
          emptyDir: {}

