apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-test-pv-claim
  labels:
    app: jenkins-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: vmware-default
